### ISSUE TITLE
ruby/2.7.0 isn't supported by this pry-doc version

### ISSUE THREAD

**Issue by sevk** [pry/pry-doc#99] opened 2020-03-25 06:06 UTC
```ruby
➜  ~ gem -v
3.1.2
➜  ~ uname -a
Linux kkar4 5.5.11-arch1-1 #1 SMP PREEMPT Sun, 22 Mar 2020 16:33:15 +0000 x86_64 GNU/Linux
➜  ~ ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]
➜  ~ gem update --system
Latest version already installed. Done.
➜  ~ gem i pry-doc
Successfully installed pry-doc-1.0.0
1 gem installed
➜  ~ pry
"x86_64-linux"
ruby/2.7.0 isn't supported by this pry-doc version
[1] pry(main)> 
```

**Comment by kyrylo** [comment] 2020-03-25 06:59
I should cut a new release, the support is on master.

**Comment by kyrylo** [comment] 2020-03-26 16:01
Btw, this is a duplicate of https://github.com/pry/pry-doc/issues/95, so closing.

**Closed by kyrylo** 2020-03-26 16:01 UTC
